README.md
SkySync is a smart outdoor activity planner and wardrobe assistant that integrates real-time weather data to help users make informed decisions about their daily plans. The system provides weather forecasts, personalized activity recommendations, and outfit suggestions based on current conditions. SkySync does not only focus on outdoor activities—when weather conditions are unfavorable, it also recommends indoor activities to ensure users can still make the most of their day. By combining web and mobile applications, SkySync enhances convenience and ensures users are always prepared, whether they’re heading outside or staying indoors.
=> bacalso - SkySync 

backend/backend/.gitattributes, backend/backend/.gitignore, backend/backend/.mvn/wrapper/maven-wrapper.properties, backend/backend/mvnw, backend/backend/mvnw.cmd, backend/backend/pom.xml, backend/backend/src/main/java/edu/cit/Skysync/SkysyncApplication.java, backend/backend/src/main/resources/application.properties, backend/backend/src/test/java/edu/cit/Skysync/SkysyncApplicationTests.java
=> added backend

backend/pom.xml, backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, backend/src/main/java/edu/cit/Skysync/controller/ScheduleController.java, backend/src/main/java/edu/cit/Skysync/controller/WardrobeController.java, backend/src/main/java/edu/cit/Skysync/controller/WeatherController.java, backend/src/main/java/edu/cit/Skysync/dto/DailyWeatherDTO.java, backend/src/main/java/edu/cit/Skysync/dto/ScheduleRequestDTO.java, backend/src/main/java/edu/cit/Skysync/dto/WardrobeRecommendationDTO.java, backend/src/main/java/edu/cit/Skysync/dto/WeatherResponseDTO.java, backend/src/main/java/edu/cit/Skysync/entity/ActivityEntity.java, backend/src/main/java/edu/cit/Skysync/entity/ScheduleEntity.java, backend/src/main/java/edu/cit/Skysync/entity/UserEntity.java, backend/src/main/java/edu/cit/Skysync/repository/ActivityRepository.java, backend/src/main/java/edu/cit/Skysync/repository/ScheduleRepository.java, backend/src/main/java/edu/cit/Skysync/service/ActivityService.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, backend/src/main/java/edu/cit/Skysync/service/WardrobeService.java, backend/src/main/java/edu/cit/Skysync/service/WeatherService.java
Activity Wardrobe Schedule added
=> Activity Wardrobe Schedule added

backend/src/main/java/edu/cit/Skysync/SkysyncApplication.java, backend/src/main/java/edu/cit/Skysync/controller/NotificationController.java, backend/src/main/java/edu/cit/Skysync/dto/DailyWeatherDTO.java, backend/src/main/java/edu/cit/Skysync/dto/ScheduleRequestDTO.java, backend/src/main/java/edu/cit/Skysync/entity/NotificationEntity.java, backend/src/main/java/edu/cit/Skysync/entity/ScheduleEntity.java, backend/src/main/java/edu/cit/Skysync/entity/UserEntity.java, backend/src/main/java/edu/cit/Skysync/event/ScheduleCreatedEvent.java, backend/src/main/java/edu/cit/Skysync/repository/NotificationRepository.java, backend/src/main/java/edu/cit/Skysync/repository/ScheduleRepository.java, backend/src/main/java/edu/cit/Skysync/repository/UserRepository.java, backend/src/main/java/edu/cit/Skysync/security/JwtUtil.java, backend/src/main/java/edu/cit/Skysync/service/NotificationHandler.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, backend/src/main/java/edu/cit/Skysync/service/WeatherService.java
=> Notification added

backend/src/main/java/edu/cit/Skysync/controller/AuthController.java, backend/src/main/java/edu/cit/Skysync/security/JwtFilter.java, backend/src/main/java/edu/cit/Skysync/service/TokenBlacklistService.java
=> Logout added

README.md, backend/src/main/java/edu/cit/Skysync/SkysyncApplication.java, backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, backend/src/main/java/edu/cit/Skysync/controller/NotificationController.java, backend/src/main/java/edu/cit/Skysync/controller/ScheduleController.java, backend/src/main/java/edu/cit/Skysync/controller/WardrobeController.java, backend/src/main/java/edu/cit/Skysync/dto/ActivityDTO.java, backend/src/main/java/edu/cit/Skysync/entity/NotificationEntity.java, backend/src/main/java/edu/cit/Skysync/repository/NotificationRepository.java, backend/src/main/java/edu/cit/Skysync/service/ActivityService.java, backend/src/main/java/edu/cit/Skysync/service/DailyWeatherNotificationService.java, backend/src/main/java/edu/cit/Skysync/service/NotificationHandler.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, backend/src/main/java/edu/cit/Skysync/service/WardrobeService.java, backend/src/main/java/edu/cit/Skysync/service/WeatherService.java
=> Backend Updates

backend/src/main/java/edu/cit/Skysync/config/WebConfig.java, backend/src/main/java/edu/cit/Skysync/controller/WardrobeController.java, backend/src/main/java/edu/cit/Skysync/controller/WeatherController.java, backend/src/main/java/edu/cit/Skysync/entity/WardrobeRecommendationEntity.java, backend/src/main/java/edu/cit/Skysync/repository/WardrobeRecommendationRepository.java, backend/src/main/java/edu/cit/Skysync/service/WardrobeService.java, backend/src/main/java/edu/cit/Skysync/service/WeatherService.java, frontend_web/SkySync/package-lock.json, frontend_web/SkySync/package.json, frontend_web/SkySync/src/pages/login.jsx, frontend_web/SkySync/src/pages/register.jsx, frontend_web/SkySync/src/services/authService.js, frontend_web/SkySync/src/services/userService.js
Login and Register Frontend Web Connected
=> Login and Register Frontend Web Connected

backend/src/main/java/edu/cit/Skysync/controller/UserController.java, backend/src/main/java/edu/cit/Skysync/service/UserService.java, frontend_mobile/.idea/compiler.xml, frontend_mobile/.idea/deploymentTargetSelector.xml, frontend_mobile/.idea/gradle.xml, frontend_mobile/.idea/misc.xml, frontend_mobile/.idea/vcs.xml, frontend_mobile/app/src/main/AndroidManifest.xml, frontend_mobile/app/src/main/java/com/frontend/mobile/MainActivity.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiClient.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiService.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/AuthResponse.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/LoginScreen.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/RegisterScreen.kt, frontend_mobile/app/src/main/res/xml/network_security_config.xml
mobilefrontend connect backend
=> mobilefrontend connect backend

backend/src/main/java/edu/cit/Skysync/SkysyncApplication.java, backend/src/main/java/edu/cit/Skysync/config/CorsConfig.java, backend/src/main/java/edu/cit/Skysync/config/CorsFilterConfig.java, backend/src/main/java/edu/cit/Skysync/config/WebConfig.java, backend/src/main/java/edu/cit/Skysync/controller/UserController.java, backend/src/main/java/edu/cit/Skysync/controller/WardrobeController.java, backend/src/main/java/edu/cit/Skysync/controller/WeatherController.java, backend/src/main/java/edu/cit/Skysync/security/SecurityConfig.java, frontend_mobile/app/build.gradle.kts, frontend_mobile/app/src/main/AndroidManifest.xml, frontend_web/SkySync/package-lock.json, frontend_web/SkySync/package.json, frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/login.jsx, frontend_web/SkySync/src/pages/userprofile.jsx, frontend_web/SkySync/src/services/authService.js, frontend_web/SkySync/src/services/userService.js, frontend_web/SkySync/src/services/wardrobeService.js, frontend_web/SkySync/src/services/weatherService.js
frontend dashboard connected and mobile re pushed changes
=> frontend dashboard connected and mobile re pushed changes

backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, backend/src/main/java/edu/cit/Skysync/dto/ScheduleRequestDTO.java, backend/src/main/java/edu/cit/Skysync/entity/ActivityEntity.java, backend/src/main/java/edu/cit/Skysync/entity/NotificationEntity.java, backend/src/main/java/edu/cit/Skysync/entity/ScheduleEntity.java, backend/src/main/java/edu/cit/Skysync/service/WardrobeService.java, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/userprofile.jsx, frontend_web/SkySync/src/services/activityService.js, frontend_web/SkySync/src/services/userService.js
frontend web dashboard backend connected
=> frontend web dashboard backend connected

frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/recommendedwardrobe.jsx, frontend_web/SkySync/src/pages/weeklyforecast.jsx, frontend_web/SkySync/src/services/weatherService.js
weekly forecast and recommended wardrobe added
=> weekly forecast and recommended wardrobe added

backend/src/main/java/edu/cit/Skysync/SkysyncApplication.java, backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, backend/src/main/java/edu/cit/Skysync/controller/ScheduleController.java, backend/src/main/java/edu/cit/Skysync/dto/ScheduleRequestDTO.java, backend/src/main/java/edu/cit/Skysync/entity/ActivityEntity.java, backend/src/main/java/edu/cit/Skysync/entity/RecommendedActivityEntity.java, backend/src/main/java/edu/cit/Skysync/entity/ScheduleEntity.java, backend/src/main/java/edu/cit/Skysync/entity/UserEntity.java, backend/src/main/java/edu/cit/Skysync/repository/RecommendedActivityRepository.java, backend/src/main/java/edu/cit/Skysync/service/ActivityService.java, backend/src/main/java/edu/cit/Skysync/service/NotificationJob.java, backend/src/main/java/edu/cit/Skysync/service/QuartzConfig.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/myactivity.jsx, frontend_web/SkySync/src/pages/recommendedactivity.jsx, frontend_web/SkySync/src/services/activityService.js
frontend-web-add-activity-recommendation-added
=> frontend-web-add-activity-recommendation-added

backend/src/main/java/edu/cit/Skysync/controller/NotificationController.java, backend/src/main/java/edu/cit/Skysync/controller/ScheduleController.java, backend/src/main/java/edu/cit/Skysync/entity/NotificationEntity.java, backend/src/main/java/edu/cit/Skysync/repository/ScheduleRepository.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, frontend_web/SkySync/package-lock.json, frontend_web/SkySync/package.json, frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/pages/activitydetails.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/myactivity.jsx, frontend_web/SkySync/src/pages/notification.jsx, frontend_web/SkySync/src/pages/recommendedactivity.jsx, frontend_web/SkySync/src/pages/recommendedwardrobe.jsx, frontend_web/SkySync/src/pages/scheduleactivity.jsx, frontend_web/SkySync/src/services/activityService.js, frontend_web/SkySync/src/services/notificationService.js, frontend_web/SkySync/src/services/scheduleService.js
Notification Activity Scheduler connected to frontend web
=> Notification Activity Scheduler connected to frontend web

backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiService.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/User.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/HomePage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/LoginScreen.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/profile/UserProfileScreen.kt
frontend mobile update user profile connected
=> frontend mobile update user profile connected

frontend_web/SkySync/src/components/userHeader.jsx, frontend_web/SkySync/src/pages/login.jsx, frontend_web/SkySync/src/pages/notification.jsx, frontend_web/SkySync/src/pages/register.jsx
Postioning of notification on userHeader and capitalization of firstname and lastname. login successful and registration successful prompts updated
=> userHeader,login and registration prompts update

frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/RegisterScreen.kt
=> register screen

backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, frontend_mobile/app/src/main/java/com/frontend/mobile/MainActivity.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiService.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/HomePage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/MyActivityPage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewAllRecommendedActivities.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewAllRecommendedWardrobes.kt
backend connect mobile activity
=> backend connect mobile activity

backend/src/main/java/edu/cit/Skysync/controller/NotificationController.java, backend/src/main/java/edu/cit/Skysync/controller/ScheduleController.java, frontend_mobile/app/src/main/java/com/frontend/mobile/MainActivity.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiService.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/ActivityDTO.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/NotificationDTO.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/ScheduleRequestDTO.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/model/ScheduleResponseDTO.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/HomePage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/NotificationPage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ScheduleActivity.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewAllRecommendedActivities.kt, frontend_web/SkySync/src/pages/notification.jsx, frontend_web/SkySync/src/services/notificationService.js
backend connect to mobile schedule and notification
=> backend connect to mobile schedule and notification

frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/HomePage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/MyActivityPage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/LoginScreen.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/RegisterScreen.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/profile/UserProfileScreen.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ScheduleActivity.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewAllRecommendedActivities.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewAllRecommendedWardrobes.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/ViewWeeklyForcast.kt
=> complete design

frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/NotificationPage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/loginpage/RegisterScreen.kt
finally done design notification
=> finally done design notification 

backend/src/main/resources/application.properties, frontend_mobile/app/src/main/java/com/frontend/mobile/api/ApiClient.kt, frontend_mobile/app/src/main/res/xml/network_security_config.xml, frontend_web/SkySync/src/services/activityService.js, frontend_web/SkySync/src/services/authService.js, frontend_web/SkySync/src/services/config.js, frontend_web/SkySync/src/services/notificationService.js, frontend_web/SkySync/src/services/scheduleService.js, frontend_web/SkySync/src/services/userService.js, frontend_web/SkySync/src/services/wardrobeService.js, frontend_web/SkySync/src/services/weatherService.js
=> backend springboot deployed

frontend_web/SkySync/src/components/MyActivityList.jsx, frontend_web/SkySync/src/components/TimeCard.jsx, frontend_web/SkySync/src/components/userHeader.jsx, frontend_web/SkySync/src/pages/activities.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/myactivity.jsx, frontend_web/SkySync/src/pages/notification.jsx, frontend_web/SkySync/src/pages/recommendedactivity.jsx, frontend_web/SkySync/src/pages/recommendedwardrobe.jsx, frontend_web/SkySync/src/pages/weeklyforecast.jsx, frontend_web/SkySync/src/styles/home.css
=> updates on design and header

backend/src/main/java/edu/cit/Skysync/service/ActivityService.java, frontend_web/SkySync/src/components/userHeader.jsx, frontend_web/SkySync/src/pages/dashboard.jsx, frontend_web/SkySync/src/pages/notification.jsx, frontend_web/SkySync/src/services/weatherService.js
=> debugged errors

frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/components/ActivityDetailsModal.jsx, frontend_web/SkySync/src/components/MyActivityList.jsx, frontend_web/SkySync/src/pages/myactivity.jsx, frontend_web/SkySync/src/pages/scheduleactivity.jsx
=> changes in activity modal

frontend_web/SkySync/src/pages/register.jsx
=> Email Verification

backend/src/main/java/edu/cit/Skysync/controller/ActivityController.java, backend/src/main/java/edu/cit/Skysync/entity/ScheduleEntity.java, backend/src/main/java/edu/cit/Skysync/service/ScheduleService.java, backend/src/main/resources/application.properties, frontend_web/SkySync/src/App.jsx, frontend_web/SkySync/src/components/TimeCard.jsx, frontend_web/SkySync/src/pages/myactivity.jsx, frontend_web/SkySync/src/pages/recommendedactivityweek.jsx, frontend_web/SkySync/src/pages/scheduleactivity.jsx, frontend_web/SkySync/src/pages/useraddactivity.jsx, frontend_web/SkySync/src/pages/weeklyforecast.jsx, frontend_web/SkySync/src/services/activityService.js, frontend_web/SkySync/src/services/config.js
=> new changes

frontend_mobile/.idea/misc.xml, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/ActivityDetails.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/ui/activitypage/MyActivityPage.kt, frontend_mobile/app/src/main/java/com/frontend/mobile/viewactivities/UserAddActivity.kt
=> update mobile designs
